name: Deploy `developers.ledger.com`

on:
  push:
    branches:
    - main

env:
  AWS_S3_BUCKET: ledger-developers-prd
  AWS_REGION: 'eu-west-1'
  AWS_DESTRIBUTION_ID: 'E26Z7VYP01SF30'

jobs:
  build-and-deploy:
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - name: Build
      run: bundle exec jekyll build
      env:
        JEKYLL_ENV: production
        BASEURL: /
        URL: http://developers.ledger.com
   # - name: Build
   #   uses: actions/jekyll-build-pages@v1
   #   with:
   #     source: .
   #     destination: ./_site
   #     build_revision: main
   #     verbose: true
   #     token: ${{ secrets.GITHUB_TOKEN }}
    - name: Compress site
      run: zip -r _site.zip _site
    - uses: actions/upload-artifact@v3
      with:
        name: _site
        path: _site.zip

    #- name: "Deploy to AWS S3"
    #  run: aws s3 sync ./_site/ s3://${AWS_S3_BUCKET} --delete --cache-control max-age=604800
    #- name: Invalidade CDN cache
    #  run: aws cloudfront create-invalidation --distribution-id ${AWS_DESTRIBUTION_ID} --paths "/*"
